#!/bin/bash
username='zentyal'
password='zentyal'
hostname='zentyal.local'
hgfspath='workspace.cloud.studio/sogo/'

PATH=/usr/local/bin:$PATH

sshpass -p $password ssh $username@$hostname 'cd /mnt/hgfs/'$hgfspath'; ./configure; sudo make install'